### ISSUE TITLE
WarpAffine

### ISSUE THREAD

**Issue by a-albano90** [dusty-nv/jetson-utils#54]
I'm trying to rotate an image saved in a raw uchar4 pointer but the result I get in a single color green image.

My transformation matrix is:

`	const float transform[2][3] = {{0,-1,0},{1,0,0}};
`
and then I call
```
uchar4 *temp = NULL, *temp1 = NULL;
cudaWarpAffine( temp, temp1, IMG_ROW, IMG_COL, transform);		

```
It works when I use the identity matrix, but I don't get what I am doing wrong when  calling the function.

**Comment by dusty-nv** [comment]
It looks like green is the default background color when the inverse-transformed coordinates are out-of-range of the size of the input image:

https://github.com/dusty-nv/jetson-utils/blob/1f3709f48258c2d75500c35605e8f6f4a3447afc/cuda/cudaWarp-affine.cu#L49

I probably made this green so I could easier debug it.

The function expects the width before the height, and you have the IMG_ROW before IMG_COL.   Try this:

```
cudaWarpAffine( temp, temp1, IMG_COL, IMG_ROW, transform);
```

For simplicity, it appears when I made these warp functions, the image size is kept the same, so it may not be ideal to capture the full rotate.   Different input/output dimensions would need to be added to properly support it.   In this kernel you would essentially use different input/output width & height (instead of one width/height):   https://github.com/dusty-nv/jetson-utils/blob/1f3709f48258c2d75500c35605e8f6f4a3447afc/cuda/cudaWarp-affine.cu#L29
