### ISSUE TITLE
Problem?: i use gstEncoder success, but JTOP show NVENC is OFF,why?

### ISSUE THREAD

**Issue by jcyhcs** [dusty-nv/jetson-utils#57]
hi,professor!
i use gstEncoder success encode opencv Mat frame ,and then push with RTMP, but when the program running, i use jtop tool to check HW engine status, i got that:
![image](https://user-images.githubusercontent.com/34532224/109589943-17abe300-7b46-11eb-882e-a1d65ddaddbd.png)
why? NVENC not used??
help me! i confused!

**Comment by jcyhcs** [comment]
@socieboy  @dusty-nv   please help ,thanks

**Comment by socieboy** [comment]
I believe is because the encoder used for H264 si not one of the NVIDIA encoders, it using omxh264enc, if you want to use one of the nvidia encoders you need to change this [line](https://github.com/dusty-nv/jetson-utils/blob/e101638df4e94a9d576a36644eb6c26733163f84/codec/gstEncoder.cpp#L272) for **nvv4l2h264enc** and  re-run _make_ and _sudo make install_.

I'm not sure if i'm correct but give a try and let us know.
