### ISSUE TITLE
about v4l2 camera

### ISSUE THREAD

**Issue by fduxvtech** [dusty-nv/jetson-utils#78]
Hi @dusty-nv ,

I was trying to implement  a v4l2 camera grabbing class from scratch, taking inspiration from tegra-multimedia-api and your work, whose main goal is to use user-pointer to cuda memory.
May I ask why do you have the initialization of the buffers commented out using `#if 0`;  there were problem with that? 
Why don't you use unified memory? any extra info can be useful for me, thanks!

**Comment by dusty-nv** [comment]
Hi @fduxvtech, it has been a long time since I've used that `v4l2Camera` class from jetson-utils, and that section is ifdef'd out because at the time I couldn't get `V4L2_MEMORY_USERPTR` to work (it would throw errors)

Ultimately I use v4l2src through GStreamer because it provides more options and flexibility, including the ability to decode compressed V4L2 cameras using the Jetson's hardware video decoders.
